"""Keep the browser's rules in sync with Python JSON; no package install required."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
if __name__=='__main__':
    target=ROOT.parent/'shakespeare/overlay/src/lib/nuru/aiRules.ts'
    target.parent.mkdir(parents=True,exist_ok=True)
    text='// Generated by ai/scripts/export_nuru_rules.py. Edit the Python JSON sources, then regenerate.\n'
    for symbol,name in [('NURU_TAXONOMY','nuru_taxonomy.json'),('NURU_SAFETY','safety_rules.json'),('DEMO_TAXONOMY','taxonomy.json')]:
        text+='export const '+symbol+' = '+json.dumps(json.loads((ROOT/'data'/name).read_text(encoding='utf-8')),ensure_ascii=False,indent=2)+' as const;\n'
    target.write_text(text,encoding='utf-8')
    print('Updated Shakespeare rule export.')
